remote_theme: mmistakes/minimal-mistakes
title: ❯ galah.it_
description: Galah IT

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-25WB5SXJ2Z"

plugins:
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
