remote_theme: mmistakes/minimal-mistakes
title: ❯ galah.it_
description: Galah IT

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-25WB5SXJ2Z"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap

tag_page_layout: tags
tag_page_dir: tag
permalink: /:title/
tag_permalink_style: pretty

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
      header:
        overlay_color: "#E97451"
        overlay_filter: "0.6"
        overlay_image: /images/computer-room.jpg
      excerpt: ""
